dist: bionic
language: ruby

rvm:
  - 2.5

before_install:
# install openstudio
- wget https://github.com/NREL/OpenStudio/releases/download/v3.0.0/OpenStudio-3.0.0+1c9617fa4e-Linux.deb
- sudo dpkg -i ./OpenStudio-3.0.0+1c9617fa4e-Linux.deb
# install the openstudio extension gem
- export RUBYLIB=/usr/local/openstudio-3.0.0/Ruby
- gem install openstudio-extension -v 0.2.3

install:
  - bundle install

jobs:
  include:
  - stage: test
    script:
    - rake
  - stage: deploy
    if: branch = master AND (NOT type IN (pull_request))
    before_install:
    - nvm install lts/* --latest-npm
    install:
    - npm install @semantic-release/exec
    script:
    - git config --global user.email "releases@ladybug.tools"
    - git config --global user.name "ladybugbot"
    - npx semantic-release
  - stage: deploy
    if: tag IS present
    script:
      - export CLEAN_TAG=$(echo $TRAVIS_TAG | sed 's/v//g')
      - sed -i 's/"0.0.0"/'"'$CLEAN_TAG'"'/g' honeybee-openstudio.gemspec
    deploy:
      on:
        tags: true
      provider: rubygems
      skip_cleanup: true
      api_key: $API_KEY
      gem: honeybee-openstudio
